package routes

import (
	"linecrmapi/controllers"
	"linecrmapi/middlewares"

	"github.com/gin-gonic/gin"
)

func SetRouterOrders(router *gin.Engine) {
	r := router.Group("/order")
	{
		// r.GET("/:id", middlewares.CheckAccessToken, controllers.OrdersDetail)
		// r.GET("/subs/:orderId", middlewares.CheckAccessToken, controllers.OrdersDetailByOrder)
		r.POST("", middlewares.CheckAccessToken, controllers.AddOrder)
		// r.PUT("", middlewares.CheckAccessToken, controllers.UpdateOrder)
		// r.DELETE("/:id", middlewares.CheckAccessToken, controllers.DelOrder)
		// r.DELETE("/sub/:id", middlewares.CheckAccessToken, controllers.DelOrderSub)
		// r.DELETE("/tag/:id", middlewares.CheckAccessToken, controllers.DelOrderTag)
		// r.GET("/checkordertopical/:id", middlewares.CheckAccessToken, controllers.CheckOrderTopical)
		// r.POST("/ipd", middlewares.CheckAccessToken, controllers.AddOrderQueueIPD)
	}
	return
}

/**
* @apiVersion 2.0.0
* @apiGroup Online Order
* @api {post} order  1.Add Order
* @apiDescription เพิ่มใบ Order
* @apiHeader {String}   Authorization   Bearer Token "Access Tokens"
* @apiBody {Number}  id               รหัส id
* @apiBody {Number}  shop_id          รหัสร้านที่สั่งซื้อ
* @apiBody {Number}  dpm_id           รหัสแผนก
* @apiBody {Number}  customer_online_id      รหัสลูกค้าออนไลน์
* @apiBody {String}  co_citizen_id      รหัสบัตรปปช. ลูกค้าออนไลน์
* @apiBody {String}  co_prefix      คำนำหน้าลูกค้าออนไลน์
* @apiBody {String}  co_fname      ชื่อลูกค้าออนไลน์
* @apiBody {String}  co_lname      นามสกุลลูกค้าออนไลน์
* @apiBody {String}  co_gender      เพศลูกค้าออนไลน์
* @apiBody {String}  co_email      อีเมลลูกค้าออนไลน์
* @apiBody {String}  co_tel      เบอร์โทรลูกค้าออนไลน์
* @apiBody {String}  co_birthdate      วันเกิดลูกค้าออนไลน์
* @apiBody {String}  co_address      ที่อยู่ลูกค้าออนไลน์
* @apiBody {String}  co_district      ตำบลลูกค้าออนไลน์
* @apiBody {String}  co_amphoe      อำเภอลูกค้าออนไลน์
* @apiBody {String}  co_province      จังหวัดลูกค้าออนไลน์
* @apiBody {String}  co_zipcode      รหัสไปรษณีย์ลูกค้าออนไลน์
* @apiBody {Number}  [queue_id]       รหัส OPD
* @apiBody {String}  or_datetime      วันที่ออร์เดอร์
* @apiBody {String}  or_fullname      ชื่อนามสกุล
* @apiBody {String}  or_tel           เบอร์โทร
* @apiBody {String}  or_email         อีเมล
* @apiBody {String}  [or_address]     ที่อยู่
* @apiBody {String}  or_district      ตำบล
* @apiBody {String}  or_amphoe        อำเภอ
* @apiBody {String}  or_province      จังหวัด
* @apiBody {String}  or_zipcode       รหัสไปรษณีย์
* @apiBody {String}  or_comment       หมายเหตุออร์เดอร์
* @apiBody {Number}  [or_total_price] ยอดรวมราคาสินค้า
* @apiBody {Number}  [or_discount_item]    ส่วนลดรายการ
* @apiBody {Number}  [or_discount_type_id]    ประเภทส่วนลด : 1 สกุลเงิน, 2 %
* @apiBody {Number}  [or_discount_value]    ส่วนลดท้ายบิล
* @apiBody {Number}  [or_discount]    จำนวนส่วนลด
* @apiBody {Number}  or_befor_vat     ราคารวมหลังหัดส่วนลดก่อนภาษี
* @apiBody {Number}  tax_type_id      1 ไม่มีภาษี 2 รวม 3 แยก
* @apiBody {Number}  [tax_rate]       อัตราภาษี
* @apiBody {Number}  [or_vat]         ภาษีที่คำนวณแล้ว
* @apiBody {Number}  [or_total]       รวมยอดทั้งหมดหลังภาษี
* @apiBody {Number}  or_is_active     สถานะ : 1 ปกติ, 2เสร็จสิ้น, 0 ยกเลิก
* @apiBody {String}  or_eclaim_id      1 ofc 2 lgo 3 ucs 4 sss 5 nhs 6 ssi
* @apiBody {String}  or_eclaim_rate        เบิก eclaim ได้
* @apiBody {String} or_eclaim_over        เบิก eclaim ไม่ได้
* @apiBody {String}  or_eclaim_total        เบิก eclaim รวม
* @apiBody {Object[]} [tags]          tags
* @apiBody {Object[]} subs            subs
* @apiSuccessExample Sample Request:
*   {
    "id": 0,
    "shop_id": 619,
    "dpm_id": null,
    "customer_online_id": 16,
    "co_citizen_id": "1101500531640",
    "co_prefix":"Mr.",
    "co_fname": "Test",
    "co_lname": "Dev",
    "co_gender": "ชาย",
    "co_email": "walklive7@gmail.com",
    "co_tel": "0997102829",
    "co_birthdate": "1991-01-01",
    "co_address": "-",
    "co_district":  "ข่วงเปา",
    "co_amphoe":  "จอมทอง",
    "co_province": "เชียงใหม่",
    "co_zipcode": "50160",
    "queue_id": 0,
    "or_datetime": "2025-05-16 10:00:00",
    "or_fullname": "Test Dev",
    "or_tel": "0628894926",
    "or_email": "-",
    "or_address": "-",
    "or_district": "ข่วงเปา",
    "or_amphoe": "จอมทอง",
    "or_province": "เชียงใหม่",
    "or_zipcode": "50160",
    "or_comment": "",
    "or_total_price": 85,
    "or_discount_item": 0,
    "or_discount_type_id": 1,
    "or_discount_value": 0,
    "or_discount": 0,
    "or_befor_vat": 0,
    "tax_type_id": 1,
    "tax_rate": 0,
    "or_vat": 0,
    "or_total": 85,
    "or_is_active": 1,
    "or_eclaim_id": 0,
    "or_eclaim_rate": 0,
    "or_eclaim_over": 85,
    "or_eclaim_total": 0,
    "tags": [],
    "subs": [
        {
            "id": 0,
            "shop_id": 619,
            "user_id": 0,
            "customer_id": 34916,
            "queue_id": 0,
            "queue_tab": 1,
            "product_store_id": 0,
            "course_id": 0,
            "checking_id": 93141,
            "coin_id": 0,
            "product_id": 0,
            "product_unit_id": 0,
            "room_id": 0,
            "ord_type_id": 1,
            "ord_code": "C0020",
            "ord_name": "TestLine",
            "ord_qty": 1,
            "ord_unit": "Line",
            "ord_cost": 0,
            "ord_price": 10,
            "ord_amount": 10,
            "ord_discount_type_id": 1,
            "ord_discount_item": 0,
            "ord_discount": 0,
            "tax_type_id": 1,
            "tax_rate": 0,
            "ord_vat": 0,
            "ord_total": 10,
            "ord_mother_id": 0,
            "ord_is_set": 1,
            "ord_id_set": 93143,
            "ord_set_qty": 1,
            "ord_is_use": 0,
            "ord_modify": "",
            "room_code": "",
            "room_th": "",
            "room_en": "",
            "room_type_th": "",
            "room_type_en": "",
            "label": "SetLine",
            "claim_price_lgo": 0,
            "claim_price_nhs": 0,
            "claim_price_ofc": 0,
            "claim_price_ssi": 0,
            "claim_price_sss": 0,
            "claim_price_ucs": 0
        },
        {
            "id": 0,
            "shop_id": 619,
            "user_id": 0,
            "customer_id": 34916,
            "queue_id": 0,
            "queue_tab": 1,
            "product_store_id": 0,
            "course_id": 0,
            "checking_id": 93145,
            "coin_id": 0,
            "product_id": 0,
            "product_unit_id": 0,
            "room_id": 0,
            "ord_type_id": 1,
            "ord_code": "XR0002",
            "ord_name": "linexray",
            "ord_qty": 1,
            "ord_unit": "line",
            "ord_cost": 0,
            "ord_price": 0,
            "ord_amount": 0,
            "ord_discount_type_id": 1,
            "ord_discount_item": 0,
            "ord_discount": 0,
            "tax_type_id": 1,
            "tax_rate": 0,
            "ord_vat": 0,
            "ord_total": 0,
            "ord_mother_id": 0,
            "ord_is_set": 1,
            "ord_id_set": 93143,
            "ord_set_qty": 1,
            "ord_is_use": 0,
            "ord_modify": "",
            "room_code": "",
            "room_th": "",
            "room_en": "",
            "room_type_th": "",
            "room_type_en": "",
            "label": "SetLine",
            "claim_price_lgo": 0,
            "claim_price_nhs": 0,
            "claim_price_ofc": 0,
            "claim_price_ssi": 0,
            "claim_price_sss": 0,
            "claim_price_ucs": 0
        },
        {
            "id": 0,
            "shop_id": 619,
            "user_id": 0,
            "customer_id": 34916,
            "queue_id": 0,
            "queue_tab": 1,
            "product_store_id": 0,
            "course_id": 0,
            "checking_id": 93144,
            "coin_id": 0,
            "product_id": 0,
            "product_unit_id": 0,
            "room_id": 0,
            "ord_type_id": 1,
            "ord_code": "LAB0008",
            "ord_name": "linelab",
            "ord_qty": 1,
            "ord_unit": "line",
            "ord_cost": 0,
            "ord_price": 10,
            "ord_amount": 10,
            "ord_discount_type_id": 1,
            "ord_discount_item": 0,
            "ord_discount": 0,
            "tax_type_id": 1,
            "tax_rate": 0,
            "ord_vat": 0,
            "ord_total": 10,
            "ord_mother_id": 0,
            "ord_is_set": 1,
            "ord_id_set": 93143,
            "ord_set_qty": 1,
            "ord_is_use": 0,
            "ord_modify": "",
            "room_code": "",
            "room_th": "",
            "room_en": "",
            "room_type_th": "",
            "room_type_en": "",
            "label": "SetLine",
            "claim_price_lgo": 0,
            "claim_price_nhs": 0,
            "claim_price_ofc": 0,
            "claim_price_ssi": 0,
            "claim_price_sss": 0,
            "claim_price_ucs": 0
        },
        {
            "id": 0,
            "shop_id": 619,
            "user_id": 0,
            "customer_id": 34916,
            "queue_id": 0,
            "queue_tab": 2,
            "product_store_id": 0,
            "checking_id": 0,
            "course_id": 5478,
            "coin_id": 0,
            "product_id": 0,
            "product_unit_id": 0,
            "room_id": 0,
            "ord_type_id": 2,
            "ord_code": "CO0054",
            "ord_name": "Course_is_line",
            "ord_qty": 1,
            "ord_unit": "line",
            "ord_cost": 0,
            "ord_price": 0,
            "ord_amount": 0,
            "ord_discount_type_id": 1,
            "ord_discount_item": 0,
            "ord_discount": 0,
            "tax_type_id": 1,
            "tax_rate": 0,
            "ord_vat": 0,
            "ord_total": 0,
            "ord_is_set": 0,
            "ord_id_set": null,
            "ord_is_use": 0,
            "ord_rate": 1,
            "ord_set_qty": 1,
            "ord_mother_id": 0,
            "ord_modify": "",
            "room_code": "",
            "room_th": "",
            "room_en": "",
            "room_type_th": "",
            "room_type_en": "",
            "label": "",
            "claim_price_lgo": 0,
            "claim_price_nhs": 0,
            "claim_price_ofc": 0,
            "claim_price_ssi": 0,
            "claim_price_sss": 0,
            "claim_price_ucs": 0
        },
        {
            "id": 0,
            "shop_id": 619,
            "user_id": 0,
            "customer_id": 34916,
            "queue_id": 0,
            "queue_tab": 3,
            "product_store_id": 258,
            "course_id": 5478,
            "checking_id": 0,
            "coin_id": 0,
            "product_id": 182,
            "product_unit_id": 319,
            "room_id": 0,
            "ord_type_id": 5,
            "balance": 1473,
            "ord_code": "P0001",
            "ord_name": "พาราเซตามอล online",
            "ord_qty": 10,
            "ord_unit": "เม็ด",
            "ord_cost": 0,
            "ord_price": 0,
            "ord_amount": 0,
            "ord_discount_type_id": 1,
            "ord_discount_item": 0,
            "ord_discount": 0,
            "tax_type_id": 1,
            "tax_rate": 0,
            "ord_vat": 0,
            "ord_total": 0,
            "ord_is_set": 0,
            "ord_id_set": null,
            "ord_set_qty": 10,
            "ord_is_use": 0,
            "ord_mother_id": 0,
            "ord_modify": "",
            "room_code": "",
            "room_th": "",
            "room_en": "",
            "room_type_th": "",
            "room_type_en": "",
            "topical_id": 0,
            "ord_topical": "",
            "ord_direction": "",
            "label": "CO0054:Course_is_line",
            "units": [],
            "claim_price_lgo": 2,
            "claim_price_nhs": 5,
            "claim_price_ofc": 1,
            "claim_price_ssi": 6,
            "claim_price_sss": 4,
            "claim_price_ucs": 3
        },
        {
            "id": 0,
            "shop_id": 619,
            "user_id": 0,
            "customer_id": 34916,
            "queue_id": 0,
            "queue_tab": 3,
            "product_store_id": 259,
            "course_id": 5478,
            "checking_id": 0,
            "coin_id": 0,
            "product_id": 183,
            "product_unit_id": 321,
            "room_id": 0,
            "ord_type_id": 5,
            "balance": 1674.45,
            "ord_code": "P0002",
            "ord_name": "แก้แพ้ online",
            "ord_qty": 1,
            "ord_unit": "เม็ด",
            "ord_cost": 0,
            "ord_price": 0,
            "ord_amount": 0,
            "ord_discount_type_id": 1,
            "ord_discount_item": 0,
            "ord_discount": 0,
            "tax_type_id": 1,
            "tax_rate": 0,
            "ord_vat": 0,
            "ord_total": 0,
            "ord_is_set": 0,
            "ord_id_set": null,
            "ord_set_qty": 1,
            "ord_is_use": 0,
            "ord_mother_id": 0,
            "ord_modify": "",
            "room_code": "",
            "room_th": "",
            "room_en": "",
            "room_type_th": "",
            "room_type_en": "",
            "topical_id": 0,
            "ord_topical": "",
            "ord_direction": "",
            "label": "CO0054:Course_is_line",
            "units": [],
            "claim_price_lgo": 3,
            "claim_price_nhs": 3,
            "claim_price_ofc": 3,
            "claim_price_ssi": 3,
            "claim_price_sss": 3,
            "claim_price_ucs": 3
        },
        {
            "id": 0,
            "shop_id": 619,
            "user_id": 0,
            "customer_id": 34916,
            "queue_id": 0,
            "queue_tab": 2,
            "product_store_id": 0,
            "checking_id": 0,
            "course_id": 5477,
            "coin_id": 0,
            "product_id": 0,
            "product_unit_id": 0,
            "room_id": 0,
            "ord_type_id": 2,
            "ord_code": "CO0053",
            "ord_name": "Test line",
            "ord_qty": 1,
            "ord_unit": "Test line",
            "ord_cost": 0,
            "ord_price": 10,
            "ord_amount": 10,
            "ord_discount_type_id": 1,
            "ord_discount_item": 0,
            "ord_discount": 0,
            "tax_type_id": 1,
            "tax_rate": 0,
            "ord_vat": 0,
            "ord_total": 10,
            "ord_is_set": 1,
            "ord_id_set": 5482,
            "ord_is_use": 0,
            "ord_rate": 1,
            "ord_set_qty": 1,
            "ord_mother_id": 0,
            "ord_modify": "",
            "room_code": "",
            "room_th": "",
            "room_en": "",
            "room_type_th": "",
            "room_type_en": "",
            "label": "SetLine",
            "claim_price_lgo": 0,
            "claim_price_nhs": 0,
            "claim_price_ofc": 0,
            "claim_price_ssi": 0,
            "claim_price_sss": 0,
            "claim_price_ucs": 0
        },
        {
            "id": 0,
            "shop_id": 619,
            "queue_id": 0,
            "user_id": 0,
            "customer_id": 34916,
            "ord_id": 0,
            "product_store_id": 258,
            "course_id": 0,
            "checking_id": 0,
            "coin_id": 0,
            "product_id": 182,
            "product_unit_id": 319,
            "room_id": 0,
            "ord_type_id": 3,
            "balance": 1473,
            "ord_code": "P0001",
            "ord_name": "พาราเซตามอล online",
            "ord_qty": 1,
            "ord_unit": "เม็ด",
            "ord_cost": 5,
            "ord_price": 5,
            "ord_amount": 5,
            "ord_discount_type_id": 1,
            "ord_discount_item": 0,
            "ord_discount": 0,
            "tax_type_id": 1,
            "tax_rate": 0,
            "ord_vat": 0,
            "ord_total": 5,
            "ord_is_set": 1,
            "ord_id_set": 3536,
            "ord_rate": 1,
            "ord_set_qty": 1,
            "ord_is_use": 0,
            "ord_mother_id": 0,
            "ord_modify": "",
            "room_code": "",
            "room_th": "",
            "room_en": "",
            "room_type_th": "",
            "room_type_en": "",
            "topical_id": 0,
            "ord_topical": "",
            "ord_direction": "",
            "label": "SetLine",
            "units": [
                {
                    "id": 182,
                    "product_id": 182,
                    "product_units_id": 319,
                    "pd_code": "P0001",
                    "pd_name": "พาราเซตามอล online",
                    "pu_amount": 1,
                    "pu_rate": 1,
                    "u_name": "เม็ด",
                    "psp_price_ipd": 2,
                    "psp_price_opd": 5,
                    "psp_price_ofc": 1,
                    "psp_price_lgo": 2,
                    "psp_price_ucs": 3,
                    "psp_price_sss": 4,
                    "psp_price_nhs": 5,
                    "psp_price_ssi": 6
                },
                {
                    "id": 182,
                    "product_id": 182,
                    "product_units_id": 320,
                    "pd_code": "P0001",
                    "pd_name": "พาราเซตามอล online",
                    "pu_amount": 1,
                    "pu_rate": 12,
                    "u_name": "กล่อง",
                    "psp_price_ipd": 20,
                    "psp_price_opd": 50,
                    "psp_price_ofc": 10,
                    "psp_price_lgo": 20,
                    "psp_price_ucs": 30,
                    "psp_price_sss": 40,
                    "psp_price_nhs": 50,
                    "psp_price_ssi": 60
                }
            ],
            "topicals": null,
            "claim_price_lgo": 2,
            "claim_price_nhs": 5,
            "claim_price_ofc": 1,
            "claim_price_ssi": 6,
            "claim_price_sss": 4,
            "claim_price_ucs": 3
        },
        {
            "id": 0,
            "shop_id": 619,
            "queue_id": 0,
            "user_id": 0,
            "customer_id": 34916,
            "ord_id": 0,
            "product_store_id": 259,
            "course_id": 0,
            "checking_id": 0,
            "coin_id": 0,
            "product_id": 183,
            "product_unit_id": 321,
            "room_id": 0,
            "ord_type_id": 3,
            "balance": 1674.45,
            "ord_code": "P0002",
            "ord_name": "แก้แพ้ online",
            "ord_qty": 10,
            "ord_unit": "เม็ด",
            "ord_cost": 5,
            "ord_price": 5,
            "ord_amount": 50,
            "ord_discount_type_id": 1,
            "ord_discount_item": 0,
            "ord_discount": 0,
            "tax_type_id": 1,
            "tax_rate": 0,
            "ord_vat": 0,
            "ord_total": 50,
            "ord_is_set": 1,
            "ord_id_set": 3536,
            "ord_rate": 1,
            "ord_set_qty": 10,
            "ord_is_use": 0,
            "ord_mother_id": 0,
            "ord_modify": "",
            "room_code": "",
            "room_th": "",
            "room_en": "",
            "room_type_th": "",
            "room_type_en": "",
            "topical_id": 0,
            "ord_topical": "",
            "ord_direction": "",
            "label": "SetLine",
            "units": [
                {
                    "id": 183,
                    "product_id": 183,
                    "product_units_id": 321,
                    "pd_code": "P0002",
                    "pd_name": "แก้แพ้ online",
                    "pu_amount": 1,
                    "pu_rate": 1,
                    "u_name": "เม็ด",
                    "psp_price_ipd": 3,
                    "psp_price_opd": 5,
                    "psp_price_ofc": 3,
                    "psp_price_lgo": 3,
                    "psp_price_ucs": 3,
                    "psp_price_sss": 3,
                    "psp_price_nhs": 3,
                    "psp_price_ssi": 3
                }
            ],
            "topicals": null,
            "claim_price_lgo": 3,
            "claim_price_nhs": 3,
            "claim_price_ofc": 3,
            "claim_price_ssi": 3,
            "claim_price_sss": 3,
            "claim_price_ucs": 3
        }
    ]
}
* @apiSuccess {Boolean}    status        	สถานะ : true,false
* @apiSuccess {String}     message       	ข้อความตอบกลับ
* @apiSuccess {Object}     data          	{}
* @apiSuccessExample Success-Response:
*     HTTP/1.1 200 OK
*   {
    "LabplusRequestOrder": {
        "patient": {
            "hn": "",
            "full_name": "",
            "tname": "",
            "fname": "",
            "lname": "",
            "idcard": "",
            "birthday": "",
            "sex": "",
            "doctor_name": "",
            "request_note": ""
        },
        "lab_order": null
    },
    "RequestOrder": null,
    "data": 131601, รหัส Order_id
    "message": "Add Order Success.",
    "status": true
}
*/
