package routes

import (
	"linecrmapi/controllers"
	"linecrmapi/middlewares"

	"github.com/gin-gonic/gin"
)

func SetRouterQueue(router *gin.Engine) {
	r := router.Group("/queue")
	{
		r.GET("/medicalcert/print/:mdcId", middlewares.CheckAccessToken, controllers.GetPrintMedicalCert) //use
		r.GET("/check/xray/:queueId", middlewares.CheckAccessToken, controllers.GetXRayByQue)             //use
		r.GET("/check/lab/:queueId", middlewares.CheckAccessToken, controllers.GetLabByQue)               //use
		r.POST("/aifile", middlewares.CheckPublicKey, controllers.CreateImageFileForAl)
	}
	return
}

/**
 * @apiVersion 1.0.0
 * @apiGroup Queue
 * @api {put} queue/medicalcert/print/:mdcId 1.Print Medical Cert
 * @apiParam {Number} mdcId
 * @apiDescription Print Medical Cert
 * @apiHeader {String}   Authorization   Bearer Token "Access Tokens"
 * @apiSuccess {Boolean}    status        	สถานะ : true,false
 * @apiSuccess {String}     message       	ข้อความตอบกลับ
 * @apiSuccess {Object}     data          	{}
 * @apiSuccessExample Success-Response:
 *     HTTP/1.1 200 OK
 *     {
    "data": {
        "shop_id": 619,
        "customer_id": 37,
        "mdct_th": "ใบรับรองแพทย์เจ็บป่วย",
        "mdct_en": "Medical Certificate (ILLNESS)",
        "mdct_group_id": 2,
        "id": 405,
        "medical_cert_type_id": 2,
        "user_id": 2,
        "user_fullname": "ทดสอบ เดฟ",
        "user_fullname_en": "test dev",
        "user_license": null,
        "opd_id": 97712,
        "mdc_code": "SICK0006",
        "mdc_is_print": 1,
        "mdc_create": "2024-02-09T13:49:26+07:00",
        "mdc_update": "2024-02-09T13:49:26+07:00",
        "queue_id": 748,
        "opd_code": "OPD20240110-4",
        "opd_date": "2024-02-09T00:00:00+07:00",
        "opd_bw": 0,
        "opd_ht": 0,
        "opd_bmi": 0,
        "opd_t": "",
        "opd_bsa": "",
        "opd_vas": "",
        "opd_pr": "",
        "opd_bp": "",
        "opd_rr": "",
        "opd_sys": "",
        "opd_dia": "",
        "opd_o2": "",
        "opd_fag": 1,
        "opd_alcohol": 1,
        "opd_cc": "",
        "opd_hpi": "",
        "opd_pmh": "",
        "opd_dx": "1. 0001 \n",
        "opd_iopat_le": "",
        "opd_vasc_re": "",
        "opd_vasc_le": "",
        "opd_vacc_re": "",
        "opd_vacc_le": "",
        "opd_iopat_re": "",
        "opd_ga": "",
        "opd_pe": "",
        "opd_note": "",
        "opd_sick_startdate": "2024-02-09T00:00:00+07:00",
        "opd_sick_enddate": "2024-02-29T00:00:00+07:00",
        "opd_sick_notrest": 2,
        "opd_sick_air": 1,
        "opd_is_data": "0",
        "opd_update": "2024-02-09T13:49:20+07:00",
        "opd_create": "2024-02-09T13:42:52+07:00",
        "diagnostic_code": "0001",
        "diagnostic_th": "ทดสอบแก้วินิจฉัย",
        "diagnostic_en": "Test12",
        "diagnostic_detail": "",
        "opdc_name": null,
        "opdc_value": null,
        "shop": {
            "shop_id": 619,
            "shop_nature_id": 0,
            "shop_type_id": 1,
            "shop_package_id": 0,
            "currency_id": 1,
            "currency_symbol": "&#3647;",
            "shop_code": "S00619",
            "shop_name": "Teendoi Studio",
            "shop_license": "1915211695",
            "shop_nature": "Software Development",
            "shop_tax": "55511201510",
            "shop_phone": "0832092143",
            "shop_fax": "",
            "shop_email": "teendoistudio@gmail.com",
            "shop_address": "Chiang Mai",
            "shop_district": "สันพระเนตร",
            "shop_amphoe": "สันทราย",
            "shop_province": "เชียงใหม่",
            "shop_zipcode": "50210",
            "shop_name_en": "Teendoi Studio",
            "shop_nature_en": "Test Clinic",
            "shop_address_en": "128",
            "shop_district_en": "Chang Phueak",
            "shop_amphoe_en": "Mueang Chiang Mai",
            "shop_province_en": "Chiang Mai",
            "shop_zipcode_en": "50300",
            "shop_country_en": "Thailand",
            "shop_company_name": "Teendoi Studio",
            "shop_company_name_en": "Teendoi Studio",
            "shop_company_address": "Chiang Mai",
            "shop_company_address_en": "128",
            "shop_company_district_en": "Chang Phueak",
            "shop_company_district": "สันพระเนตร",
            "shop_company_amphoe": "สันทราย",
            "shop_company_amphoe_en": "Mueang Chiang Mai",
            "shop_company_province": "เชียงใหม่",
            "shop_company_province_en": "Chiang Mai",
            "shop_company_zipcode": "50210",
            "shop_company_zipcode_en": "50300",
            "shop_company_country": "ไทย",
            "shop_company_country_en": "Thailand",
            "shop_company_tax": "-",
            "shop_company_phone": "0832092143",
            "shop_company_email": "teendoistudio@gmail.com",
            "shop_latlong": "",
            "shop_promptpay_id": "",
            "shop_promptpay_name": "",
            "shop_mother_id": 619,
            "shop_image": "https://aps-x.s3.ap-southeast-1.amazonaws.com/shop/S2cb5cd09-a8ec-4935-af87-cea46ded5c43.png",
            "shop_detail": "",
            "shop_lang": "1",
            "shop_status_id": 1,
            "shop_sms_sum": "",
            "shop_sms_all": "",
            "shop_point_exchange": "",
            "shop_drug_lowest": "5",
            "shop_drug_expire": "7",
            "shop_package_type": "",
            "shop_package_usemanager": "",
            "shop_package_useuser": "",
            "shop_package_usedoctor": "",
            "shop_package_useshop": "",
            "shop_package": "2024-05-26T00:00:00+07:00",
            "shop_expire": "2025-07-02T00:00:00+07:00",
            "shop_facebook": "",
            "shop_line": "",
            "shop_instagram": "",
            "shop_port_idcard": "456",
            "shop_print_type": "1",
            "shop_comment": "",
            "shop_connect_line_status": "0",
            "shop_paysolutions_refno": "",
            "shop_cmline": "1",
            "shop_s3_delete_id": 0,
            "shop_shipping_cost": "0.00",
            "paysolutions_merchant": "",
            "paysolutions_secretkey": "",
            "paysolutions_apikey": "",
            "paysolutions_active": "0",
            "show_product_th": "ค่ายาและค่าบริการ",
            "show_product_en": "Medicine and Service Fees",
            "show_course_check_th": "ค่ารักษาและค่าบริการ",
            "show_course_check_en": "Treatment and Service Fees",
            "show_date_id": 0,
            "show_page_id": 0,
            "print_th": 1,
            "print_en": 1,
            "print_la": 0,
            "print_a4": 1,
            "print_ca": 0,
            "print_a5": 1,
            "print_80": 1,
            "invoice_comment_id": 1,
            "invoice_comment": "หมายเหตุ ใบแจ้งหนี้ จากการตั้งค่า shop",
            "receipt_comment_id": 1,
            "receipt_comment": "หมายเหตุ ใบเสร็จรับเงิน จากการตั้งค่า shop",
            "tax_comment_id": 1,
            "tax_comment": "หมายเหตุ ใบกำกับภาษี จากการตั้งค่า shop",
            "purchase_comment_id": 1,
            "purchase_comment": "หมายเหตุ ใบสั่งซื้อ จากการตั้งค่า shop",
            "transfer_comment_id": 1,
            "transfer_comment": "",
            "invoice_copy": 2,
            "receipt_copy": 2,
            "tax_copy": 2,
            "purchase_copy": 2,
            "transfer_copy": 2,
            "sticker_font_size": 12,
            "sticker_width": 70,
            "sticker_height": 50,
            "sticker_show_name": 1,
            "sticker_show_address": 1,
            "sticker_show_tel": 1,
            "sticker_show_date": 1,
            "sticker_show_expdate": 1,
            "sticker_show_detail": 1
        },
        "customer": {
            "id": 37,
            "shop_id": 619,
            "customer_group_id": 1,
            "user_id": 2,
            "ctm_id": "HN00037",
            "ctm_citizen_id": "1101500531640",
            "ctm_passport_id": "0000000000000",
            "ctm_prefix": "นาง",
            "ctm_fname": "ทดสอบ",
            "ctm_lname": "1",
            "ctm_nname": "1",
            "ctm_fname_en": "test",
            "ctm_lname_en": "1",
            "ctm_gender": "หญิง",
            "ctm_nation": "ลาว",
            "ctm_religion": "คริสต์",
            "ctm_edu_level": "มัธยมศึกษาตอนต้น",
            "ctm_marital_status": "สมรส",
            "ctm_blood": "A (เอ)",
            "ctm_email": "phanuphong.du@gmail.com",
            "ctm_tel": "0835652123",
            "ctm_tel_2": "00",
            "ctm_birthdate": "2023-08-21T00:00:00+07:00",
            "ctm_address": "11",
            "ctm_district": "ในเมือง",
            "ctm_amphoe": "เมืองลำพูน",
            "ctm_province": "ลำพูน",
            "ctm_zipcode": "51000",
            "ctm_comment": "0",
            "ctm_weight": 0,
            "ctm_height": 0,
            "ctm_waistline": 0,
            "ctm_chest": 0,
            "ctm_treatment_type": 2,
            "right_treatment_id": 6,
            "ctm_allergic": "0",
            "ctm_mental_health": "0",
            "ctm_disease": "0",
            "ctm_health_comment": "0",
            "ctm_image": "https://aps-x.s3.ap-southeast-1.amazonaws.com/customer/Ce158c4c8-6052-46c4-a842-bfcb3ae6a2b2.jpeg",
            "ctm_image_size": 0,
            "ctm_point": 98089,
            "ctm_coin": 9880,
            "line_token": "",
            "line_send": 0,
            "line_send_date": "0001-01-01T00:00:00Z",
            "facebook_id": "",
            "company_name": "0",
            "company_tax": "245132225669",
            "company_tel": "191",
            "company_email": "test@gmail.com",
            "company_address": "222",
            "company_district": "ต้นธง",
            "company_amphoe": "เมืองลำพูน",
            "company_province": "ลำพูน",
            "company_zipcode": "51000",
            "ctm_subscribe_opd": 1,
            "ctm_subscribe_lab": 1,
            "ctm_subscribe_cert": 1,
            "ctm_subscribe_receipt": 1,
            "ctm_subscribe_appoint": 1,
            "ctm_is_active": 1,
            "ctm_is_del": 0,
            "ctm_create": "2023-07-23T12:05:49+07:00",
            "ctm_update": "2024-06-14T14:43:10+07:00",
            "ctm_subscribe_pdpa_token": "",
            "ctm_subscribe_pdpa_image": "",
            "cg_name": "group - 619 - 1",
            "cg_save_type": 2,
            "cg_save": 1,
            "rt_code": "SOF",
            "rt_name": "สิทธิประกันสังคม/สิทธิข้าราชการ/สิทธิหน่วยงานรัฐ",
            "rt_name_en": "-"
        }
    },
    "message": "",
    "status": true
}
*/

/**
 * @apiVersion 1.0.0
 * @apiGroup Queue
 * @api {get} queue/check/xray/:queueId 2.Get XRay ByQue
 * @apiDescription Get XRay ByQue
 * @apiHeader {String}   Authorization   Bearer Token "Access Tokens"
 * @apiParam {Number}       queueId       queue_Id
 * @apiSuccess {Boolean}    status        	สถานะ : true,false
 * @apiSuccess {String}     message       	ข้อความตอบกลับ
 * @apiSuccess {Object}     data          	{}
 * @apiSuccessExample Success-Response:
 *     HTTP/1.1 200 OK
{
    "data": {
        "queue_id": 96760,
        "que_code": "OPD20240150",
        "que_note": "",
        "que_directions": "",
        "shop_id": 619,
        "shop": {
            "shop_id": 619,
            "shop_nature_id": 0,
            "shop_type_id": 1,
            "shop_package_id": 0,
            "currency_id": 1,
            "currency_symbol": "&#3647;",
            "shop_code": "S00619",
            "shop_name": "Teendoi Studio",
            "shop_license": "1915211695",
            "shop_nature": "Software Development",
            "shop_tax": "55511201510",
            "shop_phone": "0832092143",
            "shop_fax": "",
            "shop_email": "teendoistudio@gmail.com",
            "shop_address": "Chiang Mai",
            "shop_district": "สันพระเนตร",
            "shop_amphoe": "สันทราย",
            "shop_province": "เชียงใหม่",
            "shop_zipcode": "50210",
            "shop_name_en": "Teendoi Studio",
            "shop_nature_en": "Test Clinic",
            "shop_address_en": "128",
            "shop_district_en": "Chang Phueak",
            "shop_amphoe_en": "Mueang Chiang Mai",
            "shop_province_en": "Chiang Mai",
            "shop_zipcode_en": "50300",
            "shop_country_en": "Thailand",
            "shop_company_name": "Teendoi Studio",
            "shop_company_name_en": "Teendoi Studio",
            "shop_company_address": "Chiang Mai",
            "shop_company_address_en": "128",
            "shop_company_district_en": "Chang Phueak",
            "shop_company_district": "สันพระเนตร",
            "shop_company_amphoe": "สันทราย",
            "shop_company_amphoe_en": "Mueang Chiang Mai",
            "shop_company_province": "เชียงใหม่",
            "shop_company_province_en": "Chiang Mai",
            "shop_company_zipcode": "50210",
            "shop_company_zipcode_en": "50300",
            "shop_company_country": "ไทย",
            "shop_company_country_en": "Thailand",
            "shop_company_tax": "-",
            "shop_company_phone": "0832092143",
            "shop_company_email": "teendoistudio@gmail.com",
            "shop_latlong": "",
            "shop_promptpay_id": "",
            "shop_promptpay_name": "",
            "shop_mother_id": 619,
            "shop_image": "https://aps-x.s3.ap-southeast-1.amazonaws.com/shop/S2cb5cd09-a8ec-4935-af87-cea46ded5c43.png",
            "shop_detail": "",
            "shop_lang": "1",
            "shop_status_id": 1,
            "shop_sms_sum": "",
            "shop_sms_all": "",
            "shop_point_exchange": "",
            "shop_drug_lowest": "5",
            "shop_drug_expire": "7",
            "shop_package_type": "",
            "shop_package_usemanager": "",
            "shop_package_useuser": "",
            "shop_package_usedoctor": "",
            "shop_package_useshop": "",
            "shop_package": "2024-05-26T00:00:00+07:00",
            "shop_expire": "2025-07-02T00:00:00+07:00",
            "shop_facebook": "",
            "shop_line": "",
            "shop_instagram": "",
            "shop_port_idcard": "456",
            "shop_print_type": "1",
            "shop_comment": "",
            "shop_connect_line_status": "0",
            "shop_paysolutions_refno": "",
            "shop_cmline": "1",
            "shop_s3_delete_id": 0,
            "shop_shipping_cost": "0.00",
            "paysolutions_merchant": "",
            "paysolutions_secretkey": "",
            "paysolutions_apikey": "",
            "paysolutions_active": "0",
            "show_product_th": "ค่ายาและค่าบริการ",
            "show_product_en": "Medicine and Service Fees",
            "show_course_check_th": "ค่ารักษาและค่าบริการ",
            "show_course_check_en": "Treatment and Service Fees",
            "show_date_id": 0,
            "show_page_id": 0,
            "print_th": 1,
            "print_en": 1,
            "print_la": 0,
            "print_a4": 1,
            "print_ca": 0,
            "print_a5": 1,
            "print_80": 1,
            "invoice_comment_id": 1,
            "invoice_comment": "หมายเหตุ ใบแจ้งหนี้ จากการตั้งค่า shop",
            "receipt_comment_id": 1,
            "receipt_comment": "หมายเหตุ ใบเสร็จรับเงิน จากการตั้งค่า shop",
            "tax_comment_id": 1,
            "tax_comment": "หมายเหตุ ใบกำกับภาษี จากการตั้งค่า shop",
            "purchase_comment_id": 1,
            "purchase_comment": "หมายเหตุ ใบสั่งซื้อ จากการตั้งค่า shop",
            "transfer_comment_id": 1,
            "transfer_comment": "",
            "invoice_copy": 2,
            "receipt_copy": 2,
            "tax_copy": 2,
            "purchase_copy": 2,
            "transfer_copy": 2,
            "sticker_font_size": 12,
            "sticker_width": 70,
            "sticker_height": 50,
            "sticker_show_name": 1,
            "sticker_show_address": 1,
            "sticker_show_tel": 1,
            "sticker_show_date": 1,
            "sticker_show_expdate": 1,
            "sticker_show_detail": 1
        },
        "customer": {
            "id": 37,
            "shop_id": 619,
            "customer_group_id": 1,
            "user_id": 2,
            "ctm_id": "HN00037",
            "ctm_citizen_id": "1101500531640",
            "ctm_passport_id": "0000000000000",
            "ctm_prefix": "นาง",
            "ctm_fname": "ทดสอบ",
            "ctm_lname": "1",
            "ctm_nname": "1",
            "ctm_fname_en": "test",
            "ctm_lname_en": "1",
            "ctm_gender": "หญิง",
            "ctm_nation": "ลาว",
            "ctm_religion": "คริสต์",
            "ctm_edu_level": "มัธยมศึกษาตอนต้น",
            "ctm_marital_status": "สมรส",
            "ctm_blood": "A (เอ)",
            "ctm_email": "phanuphong.du@gmail.com",
            "ctm_tel": "0835652123",
            "ctm_tel_2": "00",
            "ctm_birthdate": "2023-08-21T00:00:00+07:00",
            "ctm_address": "11",
            "ctm_district": "ในเมือง",
            "ctm_amphoe": "เมืองลำพูน",
            "ctm_province": "ลำพูน",
            "ctm_zipcode": "51000",
            "ctm_comment": "0",
            "ctm_weight": 0,
            "ctm_height": 0,
            "ctm_waistline": 0,
            "ctm_chest": 0,
            "ctm_treatment_type": 2,
            "right_treatment_id": 6,
            "ctm_allergic": "0",
            "ctm_mental_health": "0",
            "ctm_disease": "0",
            "ctm_health_comment": "0",
            "ctm_image": "https://aps-x.s3.ap-southeast-1.amazonaws.com/customer/Ce158c4c8-6052-46c4-a842-bfcb3ae6a2b2.jpeg",
            "ctm_image_size": 0,
            "ctm_point": 98089,
            "ctm_coin": 9880,
            "line_token": "",
            "line_send": 0,
            "line_send_date": "0001-01-01T00:00:00Z",
            "facebook_id": "",
            "company_name": "0",
            "company_tax": "245132225669",
            "company_tel": "191",
            "company_email": "test@gmail.com",
            "company_address": "222",
            "company_district": "ต้นธง",
            "company_amphoe": "เมืองลำพูน",
            "company_province": "ลำพูน",
            "company_zipcode": "51000",
            "ctm_subscribe_opd": 1,
            "ctm_subscribe_lab": 1,
            "ctm_subscribe_cert": 1,
            "ctm_subscribe_receipt": 1,
            "ctm_subscribe_appoint": 1,
            "ctm_is_active": 1,
            "ctm_is_del": 0,
            "ctm_create": "2023-07-23T12:05:49+07:00",
            "ctm_update": "2024-06-14T14:43:10+07:00",
            "ctm_subscribe_pdpa_token": "",
            "ctm_subscribe_pdpa_image": "",
            "cg_name": "group - 619 - 1",
            "cg_save_type": 2,
            "cg_save": 1,
            "rt_code": "SOF",
            "rt_name": "สิทธิประกันสังคม/สิทธิข้าราชการ/สิทธิหน่วยงานรัฐ",
            "rt_name_en": "-"
        },
        "checks": [
            {
                "id": 163657,
                "shop_id": 619,
                "shop_name": "Teendoi Studio",
                "shop_phone": "0832092143",
                "receipt_id": 127400,
                "receipt_detail_id": 216135,
                "rec_code": "RE0326",
                "user_id": 4,
                "customer_id": 213,
                "ctm_id": "HN20240015",
                "ctm_prefix": "นางสาว",
                "ctm_fname": "111",
                "ctm_lname": "222",
                "ctm_fname_en": "",
                "ctm_lname_en": "",
                "ctm_gender": "ชาย",
                "ctm_birthdate": "0001-01-01T00:00:00Z",
                "queue_id": 96760,
                "que_code": "OPD20240150",
                "checking_id": 92910,
                "category_name": "Labplus",
                "chk_type_id": 2,
                "chk_code": "1001",
                "chk_name": "Glucose",
                "chk_unit": "labplus",
                "chk_value": "",
                "chk_upload": "",
                "chk_upload_size": 0,
                "chk_old": "",
                "direction_id": 0,
                "direction_name": "",
                "direction_detail": "",
                "chk_direction_detail": "",
                "chk_flag": "",
                "chk_date": "",
                "chk_datetime": "2024-08-07T14:51:30+07:00",
                "chk_is_print": 0,
                "chk_is_report": 0,
                "chk_is_active": 1,
                "chk_create": "2024-08-07T14:51:32+07:00",
                "chk_update": "2024-08-07T14:51:32+07:00",
                "sticker_font_size": 12,
                "sticker_width": 70,
                "sticker_height": 50
            },
            {
                "id": 163658,
                "shop_id": 619,
                "shop_name": "Teendoi Studio",
                "shop_phone": "0832092143",
                "receipt_id": 127400,
                "receipt_detail_id": 216136,
                "rec_code": "RE0326",
                "user_id": 4,
                "customer_id": 213,
                "ctm_id": "HN20240015",
                "ctm_prefix": "นางสาว",
                "ctm_fname": "111",
                "ctm_lname": "222",
                "ctm_fname_en": "",
                "ctm_lname_en": "",
                "ctm_gender": "ชาย",
                "ctm_birthdate": "0001-01-01T00:00:00Z",
                "queue_id": 96760,
                "que_code": "OPD20240150",
                "checking_id": 92911,
                "category_name": "Labplus",
                "chk_type_id": 2,
                "chk_code": "1003",
                "chk_name": "Non-fasting Glucose",
                "chk_unit": "labplus",
                "chk_value": "",
                "chk_upload": "",
                "chk_upload_size": 0,
                "chk_old": "",
                "direction_id": 0,
                "direction_name": "",
                "direction_detail": "",
                "chk_direction_detail": "",
                "chk_flag": "",
                "chk_date": "",
                "chk_datetime": "2024-08-07T14:51:30+07:00",
                "chk_is_print": 0,
                "chk_is_report": 0,
                "chk_is_active": 1,
                "chk_create": "2024-08-07T14:51:33+07:00",
                "chk_update": "2024-08-07T14:51:33+07:00",
                "sticker_font_size": 12,
                "sticker_width": 70,
                "sticker_height": 50
            },
            {
                "id": 163659,
                "shop_id": 619,
                "shop_name": "Teendoi Studio",
                "shop_phone": "0832092143",
                "receipt_id": 127400,
                "receipt_detail_id": 216137,
                "rec_code": "RE0326",
                "user_id": 4,
                "customer_id": 213,
                "ctm_id": "HN20240015",
                "ctm_prefix": "นางสาว",
                "ctm_fname": "111",
                "ctm_lname": "222",
                "ctm_fname_en": "",
                "ctm_lname_en": "",
                "ctm_gender": "ชาย",
                "ctm_birthdate": "0001-01-01T00:00:00Z",
                "queue_id": 96760,
                "que_code": "OPD20240150",
                "checking_id": 92916,
                "category_name": "Labplus",
                "chk_type_id": 2,
                "chk_code": "1004",
                "chk_name": "BUN",
                "chk_unit": "labplus",
                "chk_value": "",
                "chk_upload": "",
                "chk_upload_size": 0,
                "chk_old": "",
                "direction_id": 0,
                "direction_name": "",
                "direction_detail": "",
                "chk_direction_detail": "",
                "chk_flag": "",
                "chk_date": "",
                "chk_datetime": "2024-08-07T14:51:30+07:00",
                "chk_is_print": 0,
                "chk_is_report": 0,
                "chk_is_active": 1,
                "chk_create": "2024-08-07T14:51:33+07:00",
                "chk_update": "2024-08-07T14:51:33+07:00",
                "sticker_font_size": 12,
                "sticker_width": 70,
                "sticker_height": 50
            },
            {
                "id": 163660,
                "shop_id": 619,
                "shop_name": "Teendoi Studio",
                "shop_phone": "0832092143",
                "receipt_id": 127400,
                "receipt_detail_id": 216138,
                "rec_code": "RE0326",
                "user_id": 4,
                "customer_id": 213,
                "ctm_id": "HN20240015",
                "ctm_prefix": "นางสาว",
                "ctm_fname": "111",
                "ctm_lname": "222",
                "ctm_fname_en": "",
                "ctm_lname_en": "",
                "ctm_gender": "ชาย",
                "ctm_birthdate": "0001-01-01T00:00:00Z",
                "queue_id": 96760,
                "que_code": "OPD20240150",
                "checking_id": 92913,
                "category_name": "Labplus",
                "chk_type_id": 2,
                "chk_code": "1012",
                "chk_name": "Cholesterol",
                "chk_unit": "labplus",
                "chk_value": "",
                "chk_upload": "",
                "chk_upload_size": 0,
                "chk_old": "",
                "direction_id": 0,
                "direction_name": "",
                "direction_detail": "",
                "chk_direction_detail": "",
                "chk_flag": "",
                "chk_date": "",
                "chk_datetime": "2024-08-07T14:51:30+07:00",
                "chk_is_print": 0,
                "chk_is_report": 0,
                "chk_is_active": 1,
                "chk_create": "2024-08-07T14:51:33+07:00",
                "chk_update": "2024-08-07T14:51:33+07:00",
                "sticker_font_size": 12,
                "sticker_width": 70,
                "sticker_height": 50
            },
            {
                "id": 163661,
                "shop_id": 619,
                "shop_name": "Teendoi Studio",
                "shop_phone": "0832092143",
                "receipt_id": 127400,
                "receipt_detail_id": 216139,
                "rec_code": "RE0326",
                "user_id": 4,
                "customer_id": 213,
                "ctm_id": "HN20240015",
                "ctm_prefix": "นางสาว",
                "ctm_fname": "111",
                "ctm_lname": "222",
                "ctm_fname_en": "",
                "ctm_lname_en": "",
                "ctm_gender": "ชาย",
                "ctm_birthdate": "0001-01-01T00:00:00Z",
                "queue_id": 96760,
                "que_code": "OPD20240150",
                "checking_id": 92912,
                "category_name": "Labplus",
                "chk_type_id": 2,
                "chk_code": "1014",
                "chk_name": "HDL-Cholesterol",
                "chk_unit": "labplus",
                "chk_value": "",
                "chk_upload": "",
                "chk_upload_size": 0,
                "chk_old": "",
                "direction_id": 0,
                "direction_name": "",
                "direction_detail": "",
                "chk_direction_detail": "",
                "chk_flag": "",
                "chk_date": "",
                "chk_datetime": "2024-08-07T14:51:30+07:00",
                "chk_is_print": 0,
                "chk_is_report": 0,
                "chk_is_active": 1,
                "chk_create": "2024-08-07T14:51:34+07:00",
                "chk_update": "2024-08-07T14:51:34+07:00",
                "sticker_font_size": 12,
                "sticker_width": 70,
                "sticker_height": 50
            },
            {
                "id": 163662,
                "shop_id": 619,
                "shop_name": "Teendoi Studio",
                "shop_phone": "0832092143",
                "receipt_id": 127400,
                "receipt_detail_id": 216140,
                "rec_code": "RE0326",
                "user_id": 4,
                "customer_id": 213,
                "ctm_id": "HN20240015",
                "ctm_prefix": "นางสาว",
                "ctm_fname": "111",
                "ctm_lname": "222",
                "ctm_fname_en": "",
                "ctm_lname_en": "",
                "ctm_gender": "ชาย",
                "ctm_birthdate": "0001-01-01T00:00:00Z",
                "queue_id": 96760,
                "que_code": "OPD20240150",
                "checking_id": 92917,
                "category_name": "Labplus",
                "chk_type_id": 2,
                "chk_code": "1071",
                "chk_name": "CBC",
                "chk_unit": "labplus",
                "chk_value": "",
                "chk_upload": "",
                "chk_upload_size": 0,
                "chk_old": "",
                "direction_id": 0,
                "direction_name": "",
                "direction_detail": "",
                "chk_direction_detail": "",
                "chk_flag": "",
                "chk_date": "",
                "chk_datetime": "2024-08-07T14:51:30+07:00",
                "chk_is_print": 0,
                "chk_is_report": 0,
                "chk_is_active": 1,
                "chk_create": "2024-08-07T14:51:35+07:00",
                "chk_update": "2024-08-07T14:51:35+07:00",
                "sticker_font_size": 12,
                "sticker_width": 70,
                "sticker_height": 50
            }
        ]
    },
    "message": "Get data successful.",
    "status": true
}
*/

/**
 * @apiVersion 1.0.0
 * @apiGroup Queue
 * @api {get} queue/check/lab/:queueId 2.Get Lab ByQue
 * @apiDescription Get Lab ByQue
 * @apiHeader {String}   Authorization   Bearer Token "Access Tokens"
 * @apiParam {Number}       queueId       queue_Id
 * @apiSuccess {Boolean}    status        	สถานะ : true,false
 * @apiSuccess {String}     message       	ข้อความตอบกลับ
 * @apiSuccess {Object}     data          	{}
 * @apiSuccessExample Success-Response:
 *     HTTP/1.1 200 OK
{
    "data": {
        "queue_id": 96760,
        "que_code": "OPD20240150",
        "que_note": "",
        "que_directions": "",
        "shop_id": 619,
        "shop": {
            "shop_id": 619,
            "shop_nature_id": 0,
            "shop_type_id": 1,
            "shop_package_id": 0,
            "currency_id": 1,
            "currency_symbol": "&#3647;",
            "shop_code": "S00619",
            "shop_name": "Teendoi Studio",
            "shop_license": "1915211695",
            "shop_nature": "Software Development",
            "shop_tax": "55511201510",
            "shop_phone": "0832092143",
            "shop_fax": "",
            "shop_email": "teendoistudio@gmail.com",
            "shop_address": "Chiang Mai",
            "shop_district": "สันพระเนตร",
            "shop_amphoe": "สันทราย",
            "shop_province": "เชียงใหม่",
            "shop_zipcode": "50210",
            "shop_name_en": "Teendoi Studio",
            "shop_nature_en": "Test Clinic",
            "shop_address_en": "128",
            "shop_district_en": "Chang Phueak",
            "shop_amphoe_en": "Mueang Chiang Mai",
            "shop_province_en": "Chiang Mai",
            "shop_zipcode_en": "50300",
            "shop_country_en": "Thailand",
            "shop_company_name": "Teendoi Studio",
            "shop_company_name_en": "Teendoi Studio",
            "shop_company_address": "Chiang Mai",
            "shop_company_address_en": "128",
            "shop_company_district_en": "Chang Phueak",
            "shop_company_district": "สันพระเนตร",
            "shop_company_amphoe": "สันทราย",
            "shop_company_amphoe_en": "Mueang Chiang Mai",
            "shop_company_province": "เชียงใหม่",
            "shop_company_province_en": "Chiang Mai",
            "shop_company_zipcode": "50210",
            "shop_company_zipcode_en": "50300",
            "shop_company_country": "ไทย",
            "shop_company_country_en": "Thailand",
            "shop_company_tax": "-",
            "shop_company_phone": "0832092143",
            "shop_company_email": "teendoistudio@gmail.com",
            "shop_latlong": "",
            "shop_promptpay_id": "",
            "shop_promptpay_name": "",
            "shop_mother_id": 619,
            "shop_image": "https://aps-x.s3.ap-southeast-1.amazonaws.com/shop/S2cb5cd09-a8ec-4935-af87-cea46ded5c43.png",
            "shop_detail": "",
            "shop_lang": "1",
            "shop_status_id": 1,
            "shop_sms_sum": "",
            "shop_sms_all": "",
            "shop_point_exchange": "",
            "shop_drug_lowest": "5",
            "shop_drug_expire": "7",
            "shop_package_type": "",
            "shop_package_usemanager": "",
            "shop_package_useuser": "",
            "shop_package_usedoctor": "",
            "shop_package_useshop": "",
            "shop_package": "2024-05-26T00:00:00+07:00",
            "shop_expire": "2025-07-02T00:00:00+07:00",
            "shop_facebook": "",
            "shop_line": "",
            "shop_instagram": "",
            "shop_port_idcard": "456",
            "shop_print_type": "1",
            "shop_comment": "",
            "shop_connect_line_status": "0",
            "shop_paysolutions_refno": "",
            "shop_cmline": "1",
            "shop_s3_delete_id": 0,
            "shop_shipping_cost": "0.00",
            "paysolutions_merchant": "",
            "paysolutions_secretkey": "",
            "paysolutions_apikey": "",
            "paysolutions_active": "0",
            "show_product_th": "ค่ายาและค่าบริการ",
            "show_product_en": "Medicine and Service Fees",
            "show_course_check_th": "ค่ารักษาและค่าบริการ",
            "show_course_check_en": "Treatment and Service Fees",
            "show_date_id": 0,
            "show_page_id": 0,
            "print_th": 1,
            "print_en": 1,
            "print_la": 0,
            "print_a4": 1,
            "print_ca": 0,
            "print_a5": 1,
            "print_80": 1,
            "invoice_comment_id": 1,
            "invoice_comment": "หมายเหตุ ใบแจ้งหนี้ จากการตั้งค่า shop",
            "receipt_comment_id": 1,
            "receipt_comment": "หมายเหตุ ใบเสร็จรับเงิน จากการตั้งค่า shop",
            "tax_comment_id": 1,
            "tax_comment": "หมายเหตุ ใบกำกับภาษี จากการตั้งค่า shop",
            "purchase_comment_id": 1,
            "purchase_comment": "หมายเหตุ ใบสั่งซื้อ จากการตั้งค่า shop",
            "transfer_comment_id": 1,
            "transfer_comment": "",
            "invoice_copy": 2,
            "receipt_copy": 2,
            "tax_copy": 2,
            "purchase_copy": 2,
            "transfer_copy": 2,
            "sticker_font_size": 12,
            "sticker_width": 70,
            "sticker_height": 50,
            "sticker_show_name": 1,
            "sticker_show_address": 1,
            "sticker_show_tel": 1,
            "sticker_show_date": 1,
            "sticker_show_expdate": 1,
            "sticker_show_detail": 1
        },
        "customer": {
            "id": 37,
            "shop_id": 619,
            "customer_group_id": 1,
            "user_id": 2,
            "ctm_id": "HN00037",
            "ctm_citizen_id": "1101500531640",
            "ctm_passport_id": "0000000000000",
            "ctm_prefix": "นาง",
            "ctm_fname": "ทดสอบ",
            "ctm_lname": "1",
            "ctm_nname": "1",
            "ctm_fname_en": "test",
            "ctm_lname_en": "1",
            "ctm_gender": "หญิง",
            "ctm_nation": "ลาว",
            "ctm_religion": "คริสต์",
            "ctm_edu_level": "มัธยมศึกษาตอนต้น",
            "ctm_marital_status": "สมรส",
            "ctm_blood": "A (เอ)",
            "ctm_email": "phanuphong.du@gmail.com",
            "ctm_tel": "0835652123",
            "ctm_tel_2": "00",
            "ctm_birthdate": "2023-08-21T00:00:00+07:00",
            "ctm_address": "11",
            "ctm_district": "ในเมือง",
            "ctm_amphoe": "เมืองลำพูน",
            "ctm_province": "ลำพูน",
            "ctm_zipcode": "51000",
            "ctm_comment": "0",
            "ctm_weight": 0,
            "ctm_height": 0,
            "ctm_waistline": 0,
            "ctm_chest": 0,
            "ctm_treatment_type": 2,
            "right_treatment_id": 6,
            "ctm_allergic": "0",
            "ctm_mental_health": "0",
            "ctm_disease": "0",
            "ctm_health_comment": "0",
            "ctm_image": "https://aps-x.s3.ap-southeast-1.amazonaws.com/customer/Ce158c4c8-6052-46c4-a842-bfcb3ae6a2b2.jpeg",
            "ctm_image_size": 0,
            "ctm_point": 98089,
            "ctm_coin": 9880,
            "line_token": "",
            "line_send": 0,
            "line_send_date": "0001-01-01T00:00:00Z",
            "facebook_id": "",
            "company_name": "0",
            "company_tax": "245132225669",
            "company_tel": "191",
            "company_email": "test@gmail.com",
            "company_address": "222",
            "company_district": "ต้นธง",
            "company_amphoe": "เมืองลำพูน",
            "company_province": "ลำพูน",
            "company_zipcode": "51000",
            "ctm_subscribe_opd": 1,
            "ctm_subscribe_lab": 1,
            "ctm_subscribe_cert": 1,
            "ctm_subscribe_receipt": 1,
            "ctm_subscribe_appoint": 1,
            "ctm_is_active": 1,
            "ctm_is_del": 0,
            "ctm_create": "2023-07-23T12:05:49+07:00",
            "ctm_update": "2024-06-14T14:43:10+07:00",
            "ctm_subscribe_pdpa_token": "",
            "ctm_subscribe_pdpa_image": "",
            "cg_name": "group - 619 - 1",
            "cg_save_type": 2,
            "cg_save": 1,
            "rt_code": "SOF",
            "rt_name": "สิทธิประกันสังคม/สิทธิข้าราชการ/สิทธิหน่วยงานรัฐ",
            "rt_name_en": "-"
        },
        "checks": []
    },
    "message": "Get data successful.",
    "status": true
}
*/
