package routes

import (
	"linecrmapi/controllers"
	"linecrmapi/middlewares"

	"github.com/gin-gonic/gin"
)

func SetRouterReceipts(router *gin.Engine) {
	r := router.Group("/receipt")
	{
		r.GET("/:id", middlewares.CheckAccessToken, controllers.ReceiptDetail)
		r.POST("", middlewares.CheckAccessToken, controllers.AddReceipt)
	}
	return
}

/**
 * @apiVersion 1.0.0
 * @apiGroup receipt
 * @api {GET} receipt/:id 1.ReceiptDetail
 * @apiParam {Number} id
 * @apiDescription ReceiptDetail
 * @apiHeader   {String}    Authorization   Bearer Token "Access Tokens"
 * @apiSuccess {Boolean}    status        	สถานะ : true,false
 * @apiSuccess {String}     message       	ข้อความตอบกลับ
 * @apiSuccess {Object}     data          	{}
 * @apiSuccessExample Success-Response:
 *     HTTP/1.1 200 OK
 {
    "data": {
        "id": 127408,
        "shop_id": 619,
        "shop_lang": "",
        "user_id": 2,
        "customer_id": 37,
        "queue_id": 96779,
        "que_code": "OPD20240159",
        "invoice_id": 108254,
        "inv_code": "INV0232",
        "rec_code": "RE0334",
        "rec_pay_datetime": "2024-09-25T09:35:41+07:00",
        "acl_code": "T100-1",
        "acl_name": "เงินสด",
        "rec_fullname": "ทดสอบ 1",
        "rec_tel": "0835652123",
        "rec_email": "phanuphong.du@gmail.com",
        "rec_address": "11",
        "rec_district": "ในเมือง",
        "rec_amphoe": "เมืองลำพูน",
        "rec_province": "ลำพูน",
        "rec_zipcode": "51000",
        "rec_comment": "",
        "rec_total_price": 4.67,
        "rec_discount": 0,
        "rec_befor_vat": 0,
        "tax_type_id": 2,
        "tax_rate": 7,
        "rec_vat": -0.33,
        "rec_total": 5,
        "rec_payment_type": 1,
        "rec_payment_type_th": "เงินสด",
        "rec_payment_type_en": "Cash",
        "rec_type_id": 1,
        "rec_period": 1,
        "rec_pay": 5,
        "rec_balance": 0,
        "rec_pay_total": 5,
        "rec_description": "",
        "rec_account": 123456789,
        "rec_is_process": 1,
        "rec_is_active": 1,
        "rec_user_id": 2,
        "rec_user_fullname": "ทดสอบ เดฟ",
        "rec_user_fullname_en": "test dev",
        "user_id_cancel": 0,
        "user_fullname_cancel": "",
        "user_fullname_en_cancel": "",
        "rec_update": "2024-09-25T09:35:41+07:00",
        "rec_file": "",
        "rec_datetime": "2024-09-25T09:35:41+07:00",
        "shop": {
            "shop_id": 619,
            "shop_nature_id": 0,
            "shop_type_id": 1,
            "shop_package_id": 0,
            "currency_id": 1,
            "currency_symbol": "&#3647;",
            "shop_code": "S00619",
            "shop_name": "Teendoi Studio",
            "shop_license": "1915211695",
            "shop_nature": "Software Development",
            "shop_tax": "55511201510",
            "shop_phone": "0832092143",
            "shop_fax": "",
            "shop_email": "teendoistudio@gmail.com",
            "shop_address": "Chiang Mai",
            "shop_district": "สันพระเนตร",
            "shop_amphoe": "สันทราย",
            "shop_province": "เชียงใหม่",
            "shop_zipcode": "50210",
            "shop_name_en": "Teendoi Studio",
            "shop_nature_en": "Test Clinic",
            "shop_address_en": "128",
            "shop_district_en": "Chang Phueak",
            "shop_amphoe_en": "Mueang Chiang Mai",
            "shop_province_en": "Chiang Mai",
            "shop_zipcode_en": "50300",
            "shop_country_en": "Thailand",
            "shop_company_name": "Teendoi Studio",
            "shop_company_name_en": "Teendoi Studio",
            "shop_company_address": "Chiang Mai",
            "shop_company_address_en": "128",
            "shop_company_district_en": "Chang Phueak",
            "shop_company_district": "สันพระเนตร",
            "shop_company_amphoe": "สันทราย",
            "shop_company_amphoe_en": "Mueang Chiang Mai",
            "shop_company_province": "เชียงใหม่",
            "shop_company_province_en": "Chiang Mai",
            "shop_company_zipcode": "50210",
            "shop_company_zipcode_en": "50300",
            "shop_company_country": "ไทย",
            "shop_company_country_en": "Thailand",
            "shop_company_tax": "-",
            "shop_company_phone": "0832092143",
            "shop_company_email": "teendoistudio@gmail.com",
            "shop_latlong": "",
            "shop_promptpay_id": "",
            "shop_promptpay_name": "",
            "shop_mother_id": 619,
            "shop_image": "https://aps-x.s3.ap-southeast-1.amazonaws.com/shop/S2cb5cd09-a8ec-4935-af87-cea46ded5c43.png",
            "shop_detail": "",
            "shop_lang": "1",
            "shop_status_id": 1,
            "shop_sms_sum": "",
            "shop_sms_all": "",
            "shop_point_exchange": "",
            "shop_drug_lowest": "5",
            "shop_drug_expire": "7",
            "shop_package_type": "",
            "shop_package_usemanager": "",
            "shop_package_useuser": "",
            "shop_package_usedoctor": "",
            "shop_package_useshop": "",
            "shop_package": "2024-05-26T00:00:00+07:00",
            "shop_expire": "2025-07-02T00:00:00+07:00",
            "shop_facebook": "",
            "shop_line": "",
            "shop_instagram": "",
            "shop_port_idcard": "456",
            "shop_print_type": "1",
            "shop_comment": "",
            "shop_connect_line_status": "0",
            "shop_paysolutions_refno": "",
            "shop_cmline": "1",
            "shop_s3_delete_id": 0,
            "shop_shipping_cost": "0.00",
            "paysolutions_merchant": "",
            "paysolutions_secretkey": "",
            "paysolutions_apikey": "",
            "paysolutions_active": "0",
            "show_product_th": "ค่ายาและค่าบริการ",
            "show_product_en": "Medicine and Service Fees",
            "show_course_check_th": "ค่ารักษาและค่าบริการ",
            "show_course_check_en": "Treatment and Service Fees",
            "show_date_id": 0,
            "show_page_id": 0,
            "print_th": 1,
            "print_en": 1,
            "print_la": 0,
            "print_a4": 1,
            "print_ca": 0,
            "print_a5": 1,
            "print_80": 1,
            "invoice_comment_id": 1,
            "invoice_comment": "หมายเหตุ ใบแจ้งหนี้ จากการตั้งค่า shop",
            "receipt_comment_id": 1,
            "receipt_comment": "หมายเหตุ ใบเสร็จรับเงิน จากการตั้งค่า shop",
            "tax_comment_id": 1,
            "tax_comment": "หมายเหตุ ใบกำกับภาษี จากการตั้งค่า shop",
            "purchase_comment_id": 1,
            "purchase_comment": "หมายเหตุ ใบสั่งซื้อ จากการตั้งค่า shop",
            "transfer_comment_id": 1,
            "transfer_comment": "",
            "invoice_copy": 2,
            "receipt_copy": 2,
            "tax_copy": 2,
            "purchase_copy": 2,
            "transfer_copy": 2,
            "sticker_font_size": 12,
            "sticker_width": 70,
            "sticker_height": 50,
            "sticker_show_name": 1,
            "sticker_show_address": 1,
            "sticker_show_tel": 1,
            "sticker_show_date": 1,
            "sticker_show_expdate": 1,
            "sticker_show_detail": 1
        },
        "customer": {
            "id": 37,
            "shop_id": 619,
            "customer_group_id": 1,
            "user_id": 2,
            "ctm_id": "HN00037",
            "ctm_citizen_id": "1101500531640",
            "ctm_passport_id": "0000000000000",
            "ctm_prefix": "นาง",
            "ctm_fname": "ทดสอบ",
            "ctm_lname": "1",
            "ctm_nname": "1",
            "ctm_fname_en": "test",
            "ctm_lname_en": "1",
            "ctm_gender": "หญิง",
            "ctm_nation": "ลาว",
            "ctm_religion": "คริสต์",
            "ctm_edu_level": "มัธยมศึกษาตอนต้น",
            "ctm_marital_status": "สมรส",
            "ctm_blood": "A (เอ)",
            "ctm_email": "phanuphong.du@gmail.com",
            "ctm_tel": "0835652123",
            "ctm_tel_2": "00",
            "ctm_birthdate": "2023-08-21T00:00:00+07:00",
            "ctm_address": "11",
            "ctm_district": "ในเมือง",
            "ctm_amphoe": "เมืองลำพูน",
            "ctm_province": "ลำพูน",
            "ctm_zipcode": "51000",
            "ctm_comment": "0",
            "ctm_weight": 0,
            "ctm_height": 0,
            "ctm_waistline": 0,
            "ctm_chest": 0,
            "ctm_treatment_type": 2,
            "right_treatment_id": 6,
            "ctm_allergic": "0",
            "ctm_mental_health": "0",
            "ctm_disease": "0",
            "ctm_health_comment": "0",
            "ctm_image": "https://aps-x.s3.ap-southeast-1.amazonaws.com/customer/Ce158c4c8-6052-46c4-a842-bfcb3ae6a2b2.jpeg",
            "ctm_image_size": 0,
            "ctm_point": 98089,
            "ctm_coin": 9880,
            "line_token": "",
            "line_send": 0,
            "line_send_date": "0001-01-01T00:00:00Z",
            "facebook_id": "",
            "company_name": "0",
            "company_tax": "245132225669",
            "company_tel": "191",
            "company_email": "test@gmail.com",
            "company_address": "222",
            "company_district": "ต้นธง",
            "company_amphoe": "เมืองลำพูน",
            "company_province": "ลำพูน",
            "company_zipcode": "51000",
            "ctm_subscribe_opd": 1,
            "ctm_subscribe_lab": 1,
            "ctm_subscribe_cert": 1,
            "ctm_subscribe_receipt": 1,
            "ctm_subscribe_appoint": 1,
            "ctm_is_active": 1,
            "ctm_is_del": 0,
            "ctm_create": "2023-07-23T12:05:49+07:00",
            "ctm_update": "2024-06-14T14:43:10+07:00",
            "ctm_subscribe_pdpa_token": "",
            "ctm_subscribe_pdpa_image": "",
            "cg_name": "group - 619 - 1",
            "cg_save_type": 2,
            "cg_save": 1,
            "rt_code": "SOF",
            "rt_name": "สิทธิประกันสังคม/สิทธิข้าราชการ/สิทธิหน่วยงานรัฐ",
            "rt_name_en": "-"
        },
        "subs": [
            {
                "id": 216150,
                "receipt_id": 127408,
                "course_id": null,
                "ser_exp_date": "",
                "course_type_id": null,
                "checking_id": null,
                "product_id": 182,
                "product_store_id": 258,
                "product_unit_id": 319,
                "coin_id": null,
                "room_id": null,
                "queue_id": null,
                "invoice_detail_id": 216365,
                "recd_type_id": 3,
                "recd_code": "P0001",
                "recd_name": "พาราเซตามอล",
                "recd_qty": 1,
                "recd_set_qty": 1,
                "recd_limit_qty": 0,
                "recd_unit": "เม็ด",
                "u_name_en": "grain",
                "recd_cost": 0,
                "recd_price": 5,
                "recd_discount": 0,
                "recd_amount": 5,
                "tax_type_id": 2,
                "tax_rate": 7,
                "recd_vat": -0.33,
                "recd_total": 4.67,
                "recd_is_set": 0,
                "recd_is_active": 1,
                "recd_modify": "2024-09-25T09:35:41+07:00",
                "recd_eclaim": 0,
                "recd_discount_type_id": 1,
                "recd_discount_item": 0
            }
        ],
        "rec_discount_type_id": 1,
        "rec_discount_item": 0,
        "rec_discount_value": 0,
        "dpm_id": null,
        "rec_eclaim_id": 0,
        "rec_eclaim_rate": 0,
        "rec_eclaim_over": 4.67,
        "rec_eclaim_total": 0
    },
    "message": "",
    "status": true
}
*/

/**
* @apiGroup Online Order
* @api {post} receipt 3.Add Receipt
* @apiDescription เพิ่มใบเสร็จ
* @apiVersion 2.0.0
* @apiHeader   {String}    Authorization   Bearer Token "Access Tokens"
* @apiBody {Number}  invoice_id               รหัสใบแจ้งหนี้
* @apiSuccess {Boolean}    response สถานะ : true,false
* @apiSuccess {String} message ข้อความตอบกลับ
* @apiSuccess {Object}     data          	{}
* @apiSuccessExample Success-Response:
*     HTTP/1.1 200 OK
*   {
    "data": {
        "rec_id": 131239, รหัสใบเสร็จ
        "rec_is_process": 1 สถานะประมวลผล
    },
    "message": "Create receipt success.",
    "status": true
}
*/
